### ISSUE TITLE
No way to return admin asset.

### ISSUE THREAD

**Issue by Tylerlhess** [ben-abraham/raven-trader-pro#14]
https://github.com/ben-abraham/raven-trader-pro/blob/fe26f3a892fc483fe8f739aaca6e354747a12003/rvn_rpc.py#L134

This line removes the "!" before checking if it is there. This makes it so all asset details return as not Admin assets. 

To be fair I haven't read all the context so this might be meaningless but it seems like you should remove this line or the few lines after it that are unreachable code.

**Comment by ben-abraham** [comment]
Good catch! I'll get that patched up quickly.
