### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by alfirus** [ben-abraham/raven-trader-pro#18]
C:\raven-trader-pro-main>python main.py
12/06/2021 23:25:25 wallet_manager.py[line:208] INFO Locking 0 UTXO's from orders
12/06/2021 23:25:26 main.py[line:82] INFO App Startup
12/06/2021 23:25:28 server_orders.py[line:48] INFO Refreshing Server Orders
12/06/2021 23:25:29 server_connection.py[line:45] ERROR HTTPSConnectionPool(host='raventrader.net', port=443): Max retries exceeded with url: /api/sitedata/groupedlistings?assetName=&pageSize=25&offset=0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
Traceback (most recent call last):
  File "C:\raven-trader-pro-main\ui\server_orders.py", line 45, in full_reset
    self.refresh_listings()
  File "C:\raven-trader-pro-main\ui\server_orders.py", line 61, in refresh_listings
    self.swaps = self.orders["assets"]
TypeError: 'NoneType' object is not subscriptable

**Comment by ben-abraham** [comment]
Issue has been resolved. Server certificate had lapsed and is now updated. Apologies for the inconvenience.
